/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mysql.gui;

/**
 *
 * @author Jur Yel
 */
import java.util.ArrayList;
import javax.swing.JOptionPane;
import mysql.core.Agent;
import mysql.core.Branch;
import mysql.core.Car;
import mysql.core.CarOwner;
import mysql.core.Driver;
import mysql.dao.AgentDAO;
import mysql.dao.BranchDAO;
import mysql.dao.CarDAO;
import mysql.dao.CarOwnerDAO;
import mysql.dao.DriverDAO;

public class CarRentalUI_AgentDetails2 extends javax.swing.JFrame {

    /**
     * Creates new form CarRentalUI_AgentDetails2
     */
    private Branch theBranch;
    private ArrayList<Agent> agents;
    private CarDAO carDAO;
    private CarOwnerDAO ownerDAO;
    private DriverDAO driverDAO;
    private AgentDAO agentDAO;
    private BranchDAO branchDAO;
    private String accountID;
    
    public CarRentalUI_AgentDetails2(Branch branch, ArrayList<Agent> list,String accID){
        try{
            branchDAO = new BranchDAO();
            agentDAO = new AgentDAO();
            carDAO = new CarDAO();
            ownerDAO = new CarOwnerDAO();
            driverDAO = new DriverDAO();
        }
        catch(Exception exc){
            exc.printStackTrace();
        }
        initComponents();
        setLocationRelativeTo(null);
        theBranch = branch;
        agents = list;
        accountID = accID;
    }
    
    public CarRentalUI_AgentDetails2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel15 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jtxt_1Car1_Name = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jtxt_1CarOwner1_First = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jtxt_1CarOwner1_Last = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jtxt_1Driver1_Last = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jtxt_1Driver1_First = new javax.swing.JTextField();
        jLabel58 = new javax.swing.JLabel();
        jtxt_1CarOwner1_Contact = new javax.swing.JTextField();
        jLabel59 = new javax.swing.JLabel();
        jtxt_1Driver1_Contact = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jComboBox_1CarBrand1 = new javax.swing.JComboBox<>();
        jLabel23 = new javax.swing.JLabel();
        jComboBox_1CarType1 = new javax.swing.JComboBox<>();
        jtxt_1Car1_PlateNumber = new javax.swing.JTextField();
        jLabel79 = new javax.swing.JLabel();
        jtxt_1Car2_Name = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel80 = new javax.swing.JLabel();
        jtxt_1Car2_PlateNumber = new javax.swing.JTextField();
        jComboBox_1CarBrand2 = new javax.swing.JComboBox<>();
        jLabel29 = new javax.swing.JLabel();
        jComboBox_1CarType2 = new javax.swing.JComboBox<>();
        jLabel30 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        jtxt_1CarOwner2_First = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jtxt_1CarOwner2_Last = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        jtxt_1Driver2_Last = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jtxt_1Driver2_First = new javax.swing.JTextField();
        jLabel60 = new javax.swing.JLabel();
        jtxt_1CarOwner2_Contact = new javax.swing.JTextField();
        jLabel61 = new javax.swing.JLabel();
        jtxt_1Driver2_Contact = new javax.swing.JTextField();
        jbtn_Register = new javax.swing.JButton();
        jLabel37 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel38 = new javax.swing.JLabel();
        jtxt_2Car1_Name = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jLabel40 = new javax.swing.JLabel();
        jtxt_2CarOwner1_First = new javax.swing.JTextField();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jtxt_2CarOwner1_Last = new javax.swing.JTextField();
        jLabel43 = new javax.swing.JLabel();
        jtxt_2Driver1_Last = new javax.swing.JTextField();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jtxt_2Driver1_First = new javax.swing.JTextField();
        jtxt_2CarOwner1_Contact = new javax.swing.JTextField();
        jLabel62 = new javax.swing.JLabel();
        jtxt_2Driver1_Contact = new javax.swing.JTextField();
        jLabel63 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jComboBox_2CarBrand1 = new javax.swing.JComboBox<>();
        jLabel47 = new javax.swing.JLabel();
        jComboBox_2CarType1 = new javax.swing.JComboBox<>();
        jtxt_2Car1_PlateNumber = new javax.swing.JTextField();
        jLabel81 = new javax.swing.JLabel();
        jtxt_2Car2_Name = new javax.swing.JTextField();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel82 = new javax.swing.JLabel();
        jtxt_2Car2_PlateNumber = new javax.swing.JTextField();
        jComboBox_2CarBrand2 = new javax.swing.JComboBox<>();
        jLabel50 = new javax.swing.JLabel();
        jComboBox_2CarType2 = new javax.swing.JComboBox<>();
        jLabel51 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jLabel52 = new javax.swing.JLabel();
        jtxt_2CarOwner2_First = new javax.swing.JTextField();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jtxt_2CarOwner2_Last = new javax.swing.JTextField();
        jLabel55 = new javax.swing.JLabel();
        jtxt_2Driver2_Last = new javax.swing.JTextField();
        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jtxt_2Driver2_First = new javax.swing.JTextField();
        jLabel64 = new javax.swing.JLabel();
        jtxt_2CarOwner2_Contact = new javax.swing.JTextField();
        jtxt_2Driver2_Contact = new javax.swing.JTextField();
        jLabel65 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Josefin Sans", 0, 18)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Branch Agents Supervising");

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel16.setFont(new java.awt.Font("Josefin Sans", 0, 14)); // NOI18N
        jLabel16.setText("Agent#1 Supervises");

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel17.setFont(new java.awt.Font("Josefin Sans", 0, 14)); // NOI18N
        jLabel17.setText("Car #1");

        jtxt_1Car1_Name.setFont(new java.awt.Font("Josefin Sans", 0, 14)); // NOI18N
        jtxt_1Car1_Name.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxt_1Car1_Name.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel18.setFont(new java.awt.Font("Josefin Sans", 0, 14)); // NOI18N
        jLabel18.setText("Car Name:");

        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel19.setFont(new java.awt.Font("Josefin Sans", 0, 14)); // NOI18N
        jLabel19.setText("Car Owner:");

        jtxt_1CarOwner1_First.setFont(new java.awt.Font("Josefin Sans", 0, 14)); // NOI18N
        jtxt_1CarOwner1_First.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxt_1CarOwner1_First.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel20.setFont(new java.awt.Font("Josefin Sans", 0, 14)); // NOI18N
        jLabel20.setText("First Name:");

        jLabel21.setFont(new java.awt.Font("Josefin Sans", 0, 14)); // NOI18N
        jLabel21.setText("Last Name:");

        jtxt_1CarOwner1_Last.setFont(new java.awt.Font("Josefin Sans", 0, 14)); // NOI18N
        jtxt_1CarOwner1_Last.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxt_1CarOwner1_Last.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel25.setFont(new java.awt.Font("Josefin Sans", 0, 14)); // NOI18N
        jLabel25.setText("Driver:");

        jtxt_1Driver1_Last.setFont(new java.awt.Font("Josefin Sans", 0, 14)); // NOI18N
        jtxt_1Driver1_Last.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxt_1Driver1_Last.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel26.setFont(new java.awt.Font("Josefin Sans", 0, 14)); // NOI18N
        jLabel26.setText("Last Name:");

        jLabel27.setFont(new java.awt.Font("Josefin Sans", 0, 14)); // NOI18N
        jLabel27.setText("First Name:");

        jtxt_1Driver1_First.setFont(new java.awt.Font("Josefin Sans", 0, 14)); // NOI18N
        jtxt_1Driver1_First.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxt_1Driver1_First.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jtxt_1Driver1_First.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxt_1Driver1_FirstActionPerformed(evt);
            }
        });

        jLabel58.setFont(new java.awt.Font("Josefin Sans", 0, 14)); // NOI18N
        jLabel58.setText("Contact Number:");

        jtxt_1CarOwner1_Contact.setFont(new java.awt.Font("Josefin Sans", 0, 14)); // NOI18N
        jtxt_1CarOwner1_Contact.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxt_1CarOwner1_Contact.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel59.setFont(new java.awt.Font("Josefin Sans", 0, 14)); // NOI18N
        jLabel59.setText("Contact Number:");

        jtxt_1Driver1_Contact.setFont(new java.awt.Font("Josefin Sans", 0, 14)); // NOI18N
        jtxt_1Driver1_Contact.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxt_1Driver1_Contact.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addComponent(jLabel19)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(jLabel27)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtxt_1Driver1_First, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel26))
                            .addComponent(jLabel25))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtxt_1Driver1_Last, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel58)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtxt_1CarOwner1_Contact, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(jLabel20)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtxt_1CarOwner1_First, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                                .addComponent(jLabel21)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtxt_1CarOwner1_Last, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addComponent(jLabel59)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jtxt_1Driver1_Contact, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(jtxt_1CarOwner1_First, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21)
                    .addComponent(jtxt_1CarOwner1_Last, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel58)
                    .addComponent(jtxt_1CarOwner1_Contact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(jLabel25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(jtxt_1Driver1_First, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26)
                    .addComponent(jtxt_1Driver1_Last, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel59)
                    .addComponent(jtxt_1Driver1_Contact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel22.setFont(new java.awt.Font("Josefin Sans", 0, 14)); // NOI18N
        jLabel22.setText("Car Brand:");

        jComboBox_1CarBrand1.setFont(new java.awt.Font("Josefin Sans", 0, 14)); // NOI18N
        jComboBox_1CarBrand1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Toyota", "Suzuki", "Nissan", "Mazda", "Mitsubishi", "BMW", "Honda", "Ford" }));

        jLabel23.setFont(new java.awt.Font("Josefin Sans", 0, 14)); // NOI18N
        jLabel23.setText("Car Type:");

        jComboBox_1CarType1.setFont(new java.awt.Font("Josefin Sans", 0, 14)); // NOI18N
        jComboBox_1CarType1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sedan", "Crossover", "SUV", "Hatchback", "Pick-up", "CUV", "Roadster" }));

        jtxt_1Car1_PlateNumber.setFont(new java.awt.Font("Josefin Sans", 0, 14)); // NOI18N
        jtxt_1Car1_PlateNumber.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxt_1Car1_PlateNumber.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel79.setFont(new java.awt.Font("Josefin Sans", 0, 14)); // NOI18N
        jLabel79.setText("Plate Number:");

        jtxt_1Car2_Name.setFont(new java.awt.Font("Josefin Sans", 0, 14)); // NOI18N
        jtxt_1Car2_Name.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxt_1Car2_Name.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel24.setFont(new java.awt.Font("Josefin Sans", 0, 14)); // NOI18N
        jLabel24.setText("Car Name:");

        jLabel28.setFont(new java.awt.Font("Josefin Sans", 0, 14)); // NOI18N
        jLabel28.setText("Car #2");

        jLabel80.setFont(new java.awt.Font("Josefin Sans", 0, 14)); // NOI18N
        jLabel80.setText("Plate Number:");

        jtxt_1Car2_PlateNumber.setFont(new java.awt.Font("Josefin Sans", 0, 14)); // NOI18N
        jtxt_1Car2_PlateNumber.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxt_1Car2_PlateNumber.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jComboBox_1CarBrand2.setFont(new java.awt.Font("Josefin Sans", 0, 14)); // NOI18N
        jComboBox_1CarBrand2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Toyota", "Suzuki", "Nissan", "Mazda", "Mitsubishi", "BMW", "Honda", "Ford" }));

        jLabel29.setFont(new java.awt.Font("Josefin Sans", 0, 14)); // NOI18N
        jLabel29.setText("Car Brand:");

        jComboBox_1CarType2.setFont(new java.awt.Font("Josefin Sans", 0, 14)); // NOI18N
        jComboBox_1CarType2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sedan", "Crossover", "SUV", "Hatchback", "Pick-up", "CUV", "Roadster" }));

        jLabel30.setFont(new java.awt.Font("Josefin Sans", 0, 14)); // NOI18N
        jLabel30.setText("Car Type:");

        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel31.setFont(new java.awt.Font("Josefin Sans", 0, 14)); // NOI18N
        jLabel31.setText("Car Owner:");

        jtxt_1CarOwner2_First.setFont(new java.awt.Font("Josefin Sans", 0, 14)); // NOI18N
        jtxt_1CarOwner2_First.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxt_1CarOwner2_First.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel32.setFont(new java.awt.Font("Josefin Sans", 0, 14)); // NOI18N
        jLabel32.setText("First Name:");

        jLabel33.setFont(new java.awt.Font("Josefin Sans", 0, 14)); // NOI18N
        jLabel33.setText("Last Name:");

        jtxt_1CarOwner2_Last.setFont(new java.awt.Font("Josefin Sans", 0, 14)); // NOI18N
        jtxt_1CarOwner2_Last.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxt_1CarOwner2_Last.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel34.setFont(new java.awt.Font("Josefin Sans", 0, 14)); // NOI18N
        jLabel34.setText("Driver:");

        jtxt_1Driver2_Last.setFont(new java.awt.Font("Josefin Sans", 0, 14)); // NOI18N
        jtxt_1Driver2_Last.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxt_1Driver2_Last.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel35.setFont(new java.awt.Font("Josefin Sans", 0, 14)); // NOI18N
        jLabel35.setText("Last Name:");

        jLabel36.setFont(new java.awt.Font("Josefin Sans", 0, 14)); // NOI18N
        jLabel36.setText("First Name:");

        jtxt_1Driver2_First.setFont(new java.awt.Font("Josefin Sans", 0, 14)); // NOI18N
        jtxt_1Driver2_First.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxt_1Driver2_First.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel60.setFont(new java.awt.Font("Josefin Sans", 0, 14)); // NOI18N
        jLabel60.setText("Contact Number:");

        jtxt_1CarOwner2_Contact.setFont(new java.awt.Font("Josefin Sans", 0, 14)); // NOI18N
        jtxt_1CarOwner2_Contact.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxt_1CarOwner2_Contact.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel61.setFont(new java.awt.Font("Josefin Sans", 0, 14)); // NOI18N
        jLabel61.setText("Contact Number:");

        jtxt_1Driver2_Contact.setFont(new java.awt.Font("Josefin Sans", 0, 14)); // NOI18N
        jtxt_1Driver2_Contact.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxt_1Driver2_Contact.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addComponent(jLabel31)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(jLabel34)
                        .addGap(474, 474, 474))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel36)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtxt_1Driver2_First, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jtxt_1Driver2_Last)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel32)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtxt_1CarOwner2_First, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel35)
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addComponent(jLabel33)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtxt_1CarOwner2_Last, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addComponent(jLabel60)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtxt_1CarOwner2_Contact, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addComponent(jLabel61)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtxt_1Driver2_Contact, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(163, 163, 163)))
                .addGap(6, 6, 6))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addComponent(jLabel31)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32)
                    .addComponent(jtxt_1CarOwner2_First, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel33)
                    .addComponent(jtxt_1CarOwner2_Last, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel60)
                    .addComponent(jtxt_1CarOwner2_Contact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(jLabel34)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel36)
                    .addComponent(jtxt_1Driver2_First, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel35)
                    .addComponent(jtxt_1Driver2_Last, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel61)
                    .addComponent(jtxt_1Driver2_Contact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4))
        );

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel9Layout.createSequentialGroup()
                                        .addGap(22, 22, 22)
                                        .addComponent(jLabel18)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jtxt_1Car1_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel79))
                                    .addGroup(jPanel9Layout.createSequentialGroup()
                                        .addGap(28, 28, 28)
                                        .addComponent(jLabel23)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jComboBox_1CarType1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel22)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jComboBox_1CarBrand1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jtxt_1Car1_PlateNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel28)
                        .addGroup(jPanel9Layout.createSequentialGroup()
                            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel9Layout.createSequentialGroup()
                                    .addGap(22, 22, 22)
                                    .addComponent(jLabel24)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jtxt_1Car2_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel80))
                                .addGroup(jPanel9Layout.createSequentialGroup()
                                    .addGap(28, 28, 28)
                                    .addComponent(jLabel30)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jComboBox_1CarType2, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel29)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jComboBox_1CarBrand2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jtxt_1Car2_PlateNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))))))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel28)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel24)
                            .addComponent(jtxt_1Car2_Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel80)
                            .addComponent(jtxt_1Car2_PlateNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox_1CarType2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel30)
                            .addComponent(jComboBox_1CarBrand2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel29))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(jtxt_1Car1_Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel79)
                            .addComponent(jtxt_1Car1_PlateNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox_1CarType1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel23)
                            .addComponent(jComboBox_1CarBrand1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel22))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jbtn_Register.setBackground(new java.awt.Color(0, 0, 0));
        jbtn_Register.setFont(new java.awt.Font("Josefin Sans", 0, 18)); // NOI18N
        jbtn_Register.setForeground(new java.awt.Color(255, 255, 255));
        jbtn_Register.setText("Register Cars");
        jbtn_Register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_RegisterActionPerformed(evt);
            }
        });

        jLabel37.setFont(new java.awt.Font("Josefin Sans", 0, 14)); // NOI18N
        jLabel37.setText("Agent#2 Supervises");

        jPanel12.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel38.setFont(new java.awt.Font("Josefin Sans", 0, 14)); // NOI18N
        jLabel38.setText("Car #1");

        jtxt_2Car1_Name.setFont(new java.awt.Font("Josefin Sans", 0, 14)); // NOI18N
        jtxt_2Car1_Name.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxt_2Car1_Name.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel39.setFont(new java.awt.Font("Josefin Sans", 0, 14)); // NOI18N
        jLabel39.setText("Car Name:");

        jPanel13.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel40.setFont(new java.awt.Font("Josefin Sans", 0, 14)); // NOI18N
        jLabel40.setText("Car Owner:");

        jtxt_2CarOwner1_First.setFont(new java.awt.Font("Josefin Sans", 0, 14)); // NOI18N
        jtxt_2CarOwner1_First.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxt_2CarOwner1_First.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel41.setFont(new java.awt.Font("Josefin Sans", 0, 14)); // NOI18N
        jLabel41.setText("First Name:");

        jLabel42.setFont(new java.awt.Font("Josefin Sans", 0, 14)); // NOI18N
        jLabel42.setText("Last Name:");

        jtxt_2CarOwner1_Last.setFont(new java.awt.Font("Josefin Sans", 0, 14)); // NOI18N
        jtxt_2CarOwner1_Last.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxt_2CarOwner1_Last.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel43.setFont(new java.awt.Font("Josefin Sans", 0, 14)); // NOI18N
        jLabel43.setText("Driver:");

        jtxt_2Driver1_Last.setFont(new java.awt.Font("Josefin Sans", 0, 14)); // NOI18N
        jtxt_2Driver1_Last.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxt_2Driver1_Last.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel44.setFont(new java.awt.Font("Josefin Sans", 0, 14)); // NOI18N
        jLabel44.setText("Last Name:");

        jLabel45.setFont(new java.awt.Font("Josefin Sans", 0, 14)); // NOI18N
        jLabel45.setText("First Name:");

        jtxt_2Driver1_First.setFont(new java.awt.Font("Josefin Sans", 0, 14)); // NOI18N
        jtxt_2Driver1_First.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxt_2Driver1_First.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jtxt_2CarOwner1_Contact.setFont(new java.awt.Font("Josefin Sans", 0, 14)); // NOI18N
        jtxt_2CarOwner1_Contact.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxt_2CarOwner1_Contact.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel62.setFont(new java.awt.Font("Josefin Sans", 0, 14)); // NOI18N
        jLabel62.setText("Contact Number:");

        jtxt_2Driver1_Contact.setFont(new java.awt.Font("Josefin Sans", 0, 14)); // NOI18N
        jtxt_2Driver1_Contact.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxt_2Driver1_Contact.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel63.setFont(new java.awt.Font("Josefin Sans", 0, 14)); // NOI18N
        jLabel63.setText("Contact Number:");

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addComponent(jLabel40)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addComponent(jLabel43)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel45)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtxt_2Driver1_First, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jtxt_2Driver1_Last, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel41)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jtxt_2CarOwner1_First, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel44)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addComponent(jLabel42)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtxt_2CarOwner1_Last, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(6, 6, 6))
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addComponent(jLabel62)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtxt_2CarOwner1_Contact, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addComponent(jLabel63)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtxt_2Driver1_Contact, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addComponent(jLabel40)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel41)
                    .addComponent(jtxt_2CarOwner1_First, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel42)
                    .addComponent(jtxt_2CarOwner1_Last, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel62)
                    .addComponent(jtxt_2CarOwner1_Contact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel43)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel45)
                    .addComponent(jtxt_2Driver1_First, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel44)
                    .addComponent(jtxt_2Driver1_Last, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel63)
                    .addComponent(jtxt_2Driver1_Contact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jLabel46.setFont(new java.awt.Font("Josefin Sans", 0, 14)); // NOI18N
        jLabel46.setText("Car Brand:");

        jComboBox_2CarBrand1.setFont(new java.awt.Font("Josefin Sans", 0, 14)); // NOI18N
        jComboBox_2CarBrand1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Toyota", "Suzuki", "Nissan", "Mazda", "Mitsubishi", "BMW", "Honda", "Ford" }));

        jLabel47.setFont(new java.awt.Font("Josefin Sans", 0, 14)); // NOI18N
        jLabel47.setText("Car Type:");

        jComboBox_2CarType1.setFont(new java.awt.Font("Josefin Sans", 0, 14)); // NOI18N
        jComboBox_2CarType1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sedan", "Crossover", "SUV", "Hatchback", "Pick-up", "CUV", "Roadster" }));

        jtxt_2Car1_PlateNumber.setFont(new java.awt.Font("Josefin Sans", 0, 14)); // NOI18N
        jtxt_2Car1_PlateNumber.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxt_2Car1_PlateNumber.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel81.setFont(new java.awt.Font("Josefin Sans", 0, 14)); // NOI18N
        jLabel81.setText("Plate Number:");

        jtxt_2Car2_Name.setFont(new java.awt.Font("Josefin Sans", 0, 14)); // NOI18N
        jtxt_2Car2_Name.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxt_2Car2_Name.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel48.setFont(new java.awt.Font("Josefin Sans", 0, 14)); // NOI18N
        jLabel48.setText("Car Name:");

        jLabel49.setFont(new java.awt.Font("Josefin Sans", 0, 14)); // NOI18N
        jLabel49.setText("Car #2");

        jLabel82.setFont(new java.awt.Font("Josefin Sans", 0, 14)); // NOI18N
        jLabel82.setText("Plate Number:");

        jtxt_2Car2_PlateNumber.setFont(new java.awt.Font("Josefin Sans", 0, 14)); // NOI18N
        jtxt_2Car2_PlateNumber.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxt_2Car2_PlateNumber.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jComboBox_2CarBrand2.setFont(new java.awt.Font("Josefin Sans", 0, 14)); // NOI18N
        jComboBox_2CarBrand2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Toyota", "Suzuki", "Nissan", "Mazda", "Mitsubishi", "BMW", "Honda", "Ford" }));

        jLabel50.setFont(new java.awt.Font("Josefin Sans", 0, 14)); // NOI18N
        jLabel50.setText("Car Brand:");

        jComboBox_2CarType2.setFont(new java.awt.Font("Josefin Sans", 0, 14)); // NOI18N
        jComboBox_2CarType2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sedan", "Crossover", "SUV", "Hatchback", "Pick-up", "CUV", "Roadster" }));

        jLabel51.setFont(new java.awt.Font("Josefin Sans", 0, 14)); // NOI18N
        jLabel51.setText("Car Type:");

        jPanel14.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel52.setFont(new java.awt.Font("Josefin Sans", 0, 14)); // NOI18N
        jLabel52.setText("Car Owner:");

        jtxt_2CarOwner2_First.setFont(new java.awt.Font("Josefin Sans", 0, 14)); // NOI18N
        jtxt_2CarOwner2_First.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxt_2CarOwner2_First.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel53.setFont(new java.awt.Font("Josefin Sans", 0, 14)); // NOI18N
        jLabel53.setText("First Name:");

        jLabel54.setFont(new java.awt.Font("Josefin Sans", 0, 14)); // NOI18N
        jLabel54.setText("Last Name:");

        jtxt_2CarOwner2_Last.setFont(new java.awt.Font("Josefin Sans", 0, 14)); // NOI18N
        jtxt_2CarOwner2_Last.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxt_2CarOwner2_Last.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel55.setFont(new java.awt.Font("Josefin Sans", 0, 14)); // NOI18N
        jLabel55.setText("Driver:");

        jtxt_2Driver2_Last.setFont(new java.awt.Font("Josefin Sans", 0, 14)); // NOI18N
        jtxt_2Driver2_Last.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxt_2Driver2_Last.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel56.setFont(new java.awt.Font("Josefin Sans", 0, 14)); // NOI18N
        jLabel56.setText("Last Name:");

        jLabel57.setFont(new java.awt.Font("Josefin Sans", 0, 14)); // NOI18N
        jLabel57.setText("First Name:");

        jtxt_2Driver2_First.setFont(new java.awt.Font("Josefin Sans", 0, 14)); // NOI18N
        jtxt_2Driver2_First.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxt_2Driver2_First.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel64.setFont(new java.awt.Font("Josefin Sans", 0, 14)); // NOI18N
        jLabel64.setText("Contact Number:");

        jtxt_2CarOwner2_Contact.setFont(new java.awt.Font("Josefin Sans", 0, 14)); // NOI18N
        jtxt_2CarOwner2_Contact.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxt_2CarOwner2_Contact.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jtxt_2Driver2_Contact.setFont(new java.awt.Font("Josefin Sans", 0, 14)); // NOI18N
        jtxt_2Driver2_Contact.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxt_2Driver2_Contact.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel65.setFont(new java.awt.Font("Josefin Sans", 0, 14)); // NOI18N
        jLabel65.setText("Contact Number:");

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addComponent(jLabel52)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel55)
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel57)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtxt_2Driver2_First, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jtxt_2Driver2_Last)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel53)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jtxt_2CarOwner2_First, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel56)
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addComponent(jLabel54)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtxt_2CarOwner2_Last, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(6, 6, 6))
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addComponent(jLabel64)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtxt_2CarOwner2_Contact, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addComponent(jLabel65)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtxt_2Driver2_Contact, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addComponent(jLabel52)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel53)
                    .addComponent(jtxt_2CarOwner2_First, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel54)
                    .addComponent(jtxt_2CarOwner2_Last, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel64)
                    .addComponent(jtxt_2CarOwner2_Contact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel55)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel57)
                    .addComponent(jtxt_2Driver2_First, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel56)
                    .addComponent(jtxt_2Driver2_Last, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel65)
                    .addComponent(jtxt_2Driver2_Contact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel12Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel38)
                        .addGroup(jPanel12Layout.createSequentialGroup()
                            .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel12Layout.createSequentialGroup()
                                    .addGap(22, 22, 22)
                                    .addComponent(jLabel39)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jtxt_2Car1_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel81))
                                .addGroup(jPanel12Layout.createSequentialGroup()
                                    .addGap(28, 28, 28)
                                    .addComponent(jLabel47)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jComboBox_2CarType1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel46)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jComboBox_2CarBrand1, 0, 174, Short.MAX_VALUE)
                                .addComponent(jtxt_2Car1_PlateNumber)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel14, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel49)
                        .addGroup(jPanel12Layout.createSequentialGroup()
                            .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel12Layout.createSequentialGroup()
                                    .addGap(22, 22, 22)
                                    .addComponent(jLabel48)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jtxt_2Car2_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel82))
                                .addGroup(jPanel12Layout.createSequentialGroup()
                                    .addGap(28, 28, 28)
                                    .addComponent(jLabel51)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jComboBox_2CarType2, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel50)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jComboBox_2CarBrand2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jtxt_2Car2_PlateNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addComponent(jLabel49)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel48)
                            .addComponent(jtxt_2Car2_Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel82)
                            .addComponent(jtxt_2Car2_PlateNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox_2CarType2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel51)
                            .addComponent(jComboBox_2CarBrand2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel50))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addComponent(jLabel38)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel39)
                            .addComponent(jtxt_2Car1_Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel81)
                            .addComponent(jtxt_2Car1_PlateNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox_2CarType1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel47)
                            .addComponent(jComboBox_2CarBrand1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel46))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel16))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel37)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(489, 489, 489)
                        .addComponent(jbtn_Register, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel37)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbtn_Register, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel15)
                .addGap(507, 507, 507))
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtxt_1Driver1_FirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxt_1Driver1_FirstActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt_1Driver1_FirstActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        HomePageUI homeUI = new HomePageUI(accountID);
        homeUI.setVisible(true);
    }//GEN-LAST:event_formWindowClosed

    private void jbtn_RegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_RegisterActionPerformed
       register();
    }//GEN-LAST:event_jbtn_RegisterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CarRentalUI_AgentDetails2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CarRentalUI_AgentDetails2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CarRentalUI_AgentDetails2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CarRentalUI_AgentDetails2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CarRentalUI_AgentDetails2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox_1CarBrand1;
    private javax.swing.JComboBox<String> jComboBox_1CarBrand2;
    private javax.swing.JComboBox<String> jComboBox_1CarType1;
    private javax.swing.JComboBox<String> jComboBox_1CarType2;
    private javax.swing.JComboBox<String> jComboBox_2CarBrand1;
    private javax.swing.JComboBox<String> jComboBox_2CarBrand2;
    private javax.swing.JComboBox<String> jComboBox_2CarType1;
    private javax.swing.JComboBox<String> jComboBox_2CarType2;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel79;
    private javax.swing.JLabel jLabel80;
    private javax.swing.JLabel jLabel81;
    private javax.swing.JLabel jLabel82;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JButton jbtn_Register;
    private javax.swing.JTextField jtxt_1Car1_Name;
    private javax.swing.JTextField jtxt_1Car1_PlateNumber;
    private javax.swing.JTextField jtxt_1Car2_Name;
    private javax.swing.JTextField jtxt_1Car2_PlateNumber;
    private javax.swing.JTextField jtxt_1CarOwner1_Contact;
    private javax.swing.JTextField jtxt_1CarOwner1_First;
    private javax.swing.JTextField jtxt_1CarOwner1_Last;
    private javax.swing.JTextField jtxt_1CarOwner2_Contact;
    private javax.swing.JTextField jtxt_1CarOwner2_First;
    private javax.swing.JTextField jtxt_1CarOwner2_Last;
    private javax.swing.JTextField jtxt_1Driver1_Contact;
    private javax.swing.JTextField jtxt_1Driver1_First;
    private javax.swing.JTextField jtxt_1Driver1_Last;
    private javax.swing.JTextField jtxt_1Driver2_Contact;
    private javax.swing.JTextField jtxt_1Driver2_First;
    private javax.swing.JTextField jtxt_1Driver2_Last;
    private javax.swing.JTextField jtxt_2Car1_Name;
    private javax.swing.JTextField jtxt_2Car1_PlateNumber;
    private javax.swing.JTextField jtxt_2Car2_Name;
    private javax.swing.JTextField jtxt_2Car2_PlateNumber;
    private javax.swing.JTextField jtxt_2CarOwner1_Contact;
    private javax.swing.JTextField jtxt_2CarOwner1_First;
    private javax.swing.JTextField jtxt_2CarOwner1_Last;
    private javax.swing.JTextField jtxt_2CarOwner2_Contact;
    private javax.swing.JTextField jtxt_2CarOwner2_First;
    private javax.swing.JTextField jtxt_2CarOwner2_Last;
    private javax.swing.JTextField jtxt_2Driver1_Contact;
    private javax.swing.JTextField jtxt_2Driver1_First;
    private javax.swing.JTextField jtxt_2Driver1_Last;
    private javax.swing.JTextField jtxt_2Driver2_Contact;
    private javax.swing.JTextField jtxt_2Driver2_First;
    private javax.swing.JTextField jtxt_2Driver2_Last;
    // End of variables declaration//GEN-END:variables

    private void register(){
        try{
            int branchID = branchDAO.getBranchID(theBranch.getBranchName());
            
            String aCar1Name = jtxt_1Car1_Name.getText().trim();
            String aCar1Plate = jtxt_1Car1_PlateNumber.getText().trim();
            String aCar1Brand = jComboBox_1CarBrand1.getSelectedItem().toString();
            String aCar1Type = jComboBox_1CarType1.getSelectedItem().toString();
            String aCarOwner1First = jtxt_1CarOwner1_First.getText().trim();
            String aCarOwner1Last = jtxt_1CarOwner1_Last.getText().trim();
            String aCarOwner1Contact = jtxt_1CarOwner1_Contact.getText().trim();
            String aCarDriver1First = jtxt_1Driver1_First.getText().trim();
            String aCarDriver1Last = jtxt_1Driver1_Last.getText().trim();
            String aCarDriver1Contact = jtxt_1Driver1_Contact.getText().trim();
            
            String aCar2Name = jtxt_1Car2_Name.getText().trim();
            String aCar2Plate = jtxt_1Car2_PlateNumber.getText().trim();
            String aCar2Brand = jComboBox_1CarBrand2.getSelectedItem().toString();
            String aCar2Type = jComboBox_1CarType2.getSelectedItem().toString();
            String aCarOwner2First = jtxt_1CarOwner2_First.getText().trim();
            String aCarOwner2Last = jtxt_1CarOwner2_Last.getText().trim();
            String aCarOwner2Contact = jtxt_1CarOwner2_Contact.getText().trim();
            String aCarDriver2First = jtxt_1Driver2_First.getText().trim();
            String aCarDriver2Last = jtxt_1Driver2_Last.getText().trim();
            String aCarDriver2Contact = jtxt_1Driver2_Contact.getText().trim();
            
            String bCar1Name = jtxt_2Car1_Name.getText().trim();
            String bCar1Plate = jtxt_2Car1_PlateNumber.getText().trim();
            String bCar1Brand = jComboBox_2CarBrand1.getSelectedItem().toString();
            String bCar1Type = jComboBox_2CarType1.getSelectedItem().toString();
            String bCarOwner1First = jtxt_2CarOwner1_First.getText().trim();
            String bCarOwner1Last = jtxt_2CarOwner1_Last.getText().trim();
            String bCarOwner1Contact = jtxt_2CarOwner1_Contact.getText().trim();
            String bCarDriver1First = jtxt_2Driver1_First.getText().trim();
            String bCarDriver1Last = jtxt_2Driver1_Last.getText().trim();
            String bCarDriver1Contact = jtxt_2Driver1_Contact.getText().trim();
            
            String bCar2Name = jtxt_2Car2_Name.getText().trim();
            String bCar2Plate = jtxt_2Car2_PlateNumber.getText().trim();
            String bCar2Brand = jComboBox_2CarBrand2.getSelectedItem().toString();
            String bCar2Type = jComboBox_2CarType2.getSelectedItem().toString();
            String bCarOwner2First = jtxt_2CarOwner2_First.getText().trim();
            String bCarOwner2Last = jtxt_2CarOwner2_Last.getText().trim();
            String bCarOwner2Contact = jtxt_2CarOwner2_Contact.getText().trim();
            String bCarDriver2First = jtxt_2Driver2_First.getText().trim();
            String bCarDriver2Last = jtxt_2Driver2_Last.getText().trim();
            String bCarDriver2Contact = jtxt_2Driver2_Contact.getText().trim();
            
            ArrayList<Car> aCars = new ArrayList<>();
            ArrayList<CarOwner> aOwners  = new ArrayList<>();
            ArrayList<Driver> aDrivers = new ArrayList<>();
            
            ArrayList<Car> bCars = new ArrayList<>();
            ArrayList<CarOwner> bOwners = new ArrayList<>();
            ArrayList<Driver> bDrivers = new ArrayList<>();
            
            
            /* Encapsulate all Agent #1: Car #1 Details */
            
            if(!(aCar1Name.isEmpty()) && !(aCarOwner1First.isEmpty())){
                String ownerName = String.format("%s %s",aCarOwner1First,aCarOwner1Last);
                String agentName = String.format("%s %s",agents.get(0).getFirstName(),agents.get(0).getLastName());
                int agentID = agentDAO.getAgentID(agentName);
                
                
                Car car = new Car(aCar1Name,ownerName,aCar1Brand,aCar1Type,aCar1Plate);
                CarOwner owner = new CarOwner(theBranch.getBranchName(),agentName,aCarOwner1First,aCarOwner1Last,aCarOwner1Contact);
                owner.setAgentID(agentID);
                owner.setBranchID(branchID);
                Driver driver = new Driver(theBranch.getBranchName(),agentName,aCar1Name,aCarDriver1First,aCarDriver1Last,aCarDriver1Contact);
                driver.setAgentID(agentID);
                driver.setBranchID(branchID);
                
                aCars.add(car);
                aOwners.add(owner);
                aDrivers.add(driver);
            }
            
            /* Encapsulate all Agent #1: Car #2 Details */
            
            if(!(aCar2Name.isEmpty()) && !(aCarOwner2First.isEmpty())){
                String ownerName = String.format("%s %s",aCarOwner2First,aCarOwner2Last);
                String agentName = String.format("%s %s",agents.get(0).getFirstName(),agents.get(0).getLastName());
                int agentID = agentDAO.getAgentID(agentName);
                
                Car car = new Car(aCar2Name,ownerName,aCar2Brand,aCar2Type,aCar2Plate);
                CarOwner owner = new CarOwner(theBranch.getBranchName(),agentName,aCarOwner2First,aCarOwner2Last,aCarOwner2Contact);
                owner.setAgentID(agentID);
                owner.setBranchID(branchID);
                Driver driver = new Driver(theBranch.getBranchName(),agentName,aCar2Name,aCarDriver2First,aCarDriver2Last,aCarDriver2Contact);
                driver.setAgentID(agentID);
                driver.setBranchID(branchID);
                
                aCars.add(car);
                aOwners.add(owner);
                aDrivers.add(driver);
            }
            
            
            /* Encapsulate all Agent #2: Car #1 Details */
            
            if(!(bCar1Name.isEmpty()) && !(bCarOwner1First.isEmpty())){
                String ownerName = String.format("%s %s",bCarOwner1First,bCarOwner1Last);
                String agentName = String.format("%s %s",agents.get(1).getFirstName(),agents.get(1).getLastName());
                int agentID = agentDAO.getAgentID(agentName);
                
                Car car = new Car(bCar1Name,ownerName,bCar1Brand,bCar1Type,bCar1Plate);
                CarOwner owner = new CarOwner(theBranch.getBranchName(),agentName,bCarOwner1First,bCarOwner1Last,bCarOwner1Contact);
                owner.setAgentID(agentID);
                owner.setBranchID(branchID);
                Driver driver = new Driver(theBranch.getBranchName(),agentName,bCar1Name,bCarDriver1First,bCarDriver1Last,bCarDriver1Contact);
                driver.setAgentID(agentID);
                driver.setBranchID(branchID);
                
                bCars.add(car);
                bOwners.add(owner);
                bDrivers.add(driver);
            }
            
            /* Encapsulate all Agent #2: Car #2 Details */
            
            if(!(bCar1Name.isEmpty()) && !(bCarOwner1First.isEmpty())){
                String ownerName = String.format("%s %s",bCarOwner2First,bCarOwner2Last);
                String agentName = String.format("%s %s",agents.get(1).getFirstName(),agents.get(1).getLastName());
                int agentID = agentDAO.getAgentID(agentName);
                
                Car car = new Car(bCar2Name,ownerName,bCar2Brand,bCar2Type,bCar2Plate);
                CarOwner owner = new CarOwner(theBranch.getBranchName(),agentName,bCarOwner2First,bCarOwner2Last,bCarOwner2Contact);
                owner.setAgentID(agentID);
                owner.setBranchID(branchID);
                Driver driver = new Driver(theBranch.getBranchName(),agentName,bCar2Name,bCarDriver2First,bCarDriver2Last,bCarDriver2Contact);
                driver.setAgentID(agentID);
                driver.setBranchID(branchID);
                
                bCars.add(car);
                bOwners.add(owner);
                bDrivers.add(driver);
            }
            
            else if((!(aCar1Name.isEmpty()) && aCarOwner1First.isEmpty()) || 
                        (!(aCar2Name.isEmpty()) && aCarOwner2First.isEmpty()) || 
                        (!(bCar1Name.isEmpty()) && bCarOwner1First.isEmpty()) ||
                        (!(bCar2Name.isEmpty()) && bCarOwner2First.isEmpty())){
                JOptionPane.showMessageDialog(CarRentalUI_AgentDetails2.this,"A car must have an owner!","Register Error",JOptionPane.ERROR_MESSAGE);
            }
            
            for(int i = 0;i<aOwners.size();i++){
                String ownerName = String.format("%s %s",aOwners.get(i).getOwnerFirstName(),aOwners.get(i).getOwnerLastName());
                if(ownerDAO.checkIfOwner(ownerName)){
                    int ownerID = ownerDAO.getCarOwnerID(ownerName);
                    int carsOwned = ownerDAO.getOwnedCars(ownerName);
                    
                    ownerDAO.updateCarsOwned(ownerID,carsOwned + 1);
                }
                else{
                    CarOwner newOwner = aOwners.get(i);
                    newOwner.setOwnedCrs(1);
                    ownerDAO.AddCarOwner(newOwner);
                }
                
                String name = String.format("%s %s",aOwners.get(i).getOwnerFirstName(),aOwners.get(i).getOwnerLastName());
                int ownerID = ownerDAO.getCarOwnerID(name);
                aCars.get(i).setOwnerID(ownerID);
                
                carDAO.RegisterNewCar(aCars.get(i));
                
                int carID = carDAO.getCarID(aCars.get(i).getCarName());
                aDrivers.get(i).setCarID(carID);
                
                driverDAO.EmployDriver(aDrivers.get(i));
            }
            
            for(int i = 0;i<bOwners.size();i++){
                String ownerName = String.format("%s %s",bOwners.get(i).getOwnerFirstName(),bOwners.get(i).getOwnerLastName());
                if(ownerDAO.checkIfOwner(ownerName)){
                    int ownerID = ownerDAO.getCarOwnerID(ownerName);
                    int carsOwned = ownerDAO.getOwnedCars(ownerName);
                    
                    ownerDAO.updateCarsOwned(ownerID,carsOwned + 1);
                }
                else{
                    CarOwner newOwner = bOwners.get(i);
                    newOwner.setOwnedCrs(1);
                    ownerDAO.AddCarOwner(newOwner);
                }
                
                String name = String.format("%s %s",bOwners.get(i).getOwnerFirstName(),bOwners.get(i).getOwnerLastName());
                int ownerID = ownerDAO.getCarOwnerID(name);
                bCars.get(i).setOwnerID(ownerID);
                
                carDAO.RegisterNewCar(bCars.get(i));
                
                int carID = carDAO.getCarID(bCars.get(i).getCarName());
                bDrivers.get(i).setCarID(carID);
                
                driverDAO.EmployDriver(bDrivers.get(i));
            }
            
            int aTotalCars = aCars.size();
            int aTotalOwners = aOwners.size();
            int aTotalDrivers = aDrivers.size();
            
            int bTotalCars = bCars.size();
            int bTotalOwners = bOwners.size();
            int bTotalDrivers = bDrivers.size();
            
            JOptionPane.showMessageDialog(CarRentalUI_AgentDetails2.this,
                    "Branch: " + theBranch.getBranchName() + "\n"
                  + "Manager: " + theBranch.getBranchManagerFirst() + " " + theBranch.getBranchManagerLast() + "\n"
                  + "\tAgents: 2\n\n"
                  + "\t\tAgent #1: " + agents.get(0).getFirstName() + " " + agents.get(0).getLastName() + "\n"
                  + "\t\tSupervised Cars: " + aTotalCars + "\n"
                  + "\t\tSupervised Car Owners: " + aTotalOwners + "\n"
                  + "\t\tSupervised Drivers: " + aTotalDrivers + "\n\n"
                  + "\t\tAgent #2: " + agents.get(1).getFirstName() + " " + agents.get(1).getLastName() + "\n"
                  + "\t\tSupervised Cars: " + bTotalCars + "\n"
                  + "\t\tSupervised Car Owners: " + bTotalOwners + "\n"
                  + "\t\tSupervised Drivers: " + bTotalDrivers + "\n\n"
                  + "Branch has been registered successfully!","Register Success",JOptionPane.INFORMATION_MESSAGE);
            HomePageUI home = new HomePageUI(accountID);
            setVisible(false);
            home.setVisible(true);
            
        }
        catch(Exception exc){
            exc.printStackTrace();
        }
    }
}
