/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mysql.gui;

/**
 *
 * @author Jur Yel
 */
import java.util.ArrayList;
import javax.swing.JOptionPane;
import mysql.core.Agent;
import mysql.core.Branch;
import mysql.core.Car;
import mysql.core.CarOwner;
import mysql.core.Driver;
import mysql.dao.AgentDAO;
import mysql.dao.BranchDAO;
import mysql.dao.CarDAO;
import mysql.dao.CarOwnerDAO;
import mysql.dao.DriverDAO;

public class CarRentalUI_AgentDetails1 extends javax.swing.JFrame {

    /**
     * Creates new form CarRentalUI_AgentDetails1
     */
    private ArrayList<Agent> agents = new ArrayList<>();
    private Branch theBranch;
    private CarDAO carDAO;
    private CarOwnerDAO ownerDAO;
    private DriverDAO driverDAO;
    private AgentDAO agentDAO;
    private BranchDAO branchDAO;
    private String accountID;
    
    public CarRentalUI_AgentDetails1(Branch branch,ArrayList<Agent> list,String accID){
        try{
            carDAO = new CarDAO();
            branchDAO = new BranchDAO();
            ownerDAO = new CarOwnerDAO();
            driverDAO = new DriverDAO();
            agentDAO = new AgentDAO();
        }
        catch(Exception exc){
            exc.printStackTrace();
        }
        initComponents();
        setLocationRelativeTo(null);
        theBranch = branch;
        agents = list;
        accountID = accID;
    }
    
    public CarRentalUI_AgentDetails1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel15 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jtxt_1Car1_Name = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jtxt_1CarOwner1_First = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jtxt_1CarOwner1_Last = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jtxt_1Driver1_Last = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jtxt_1Driver1_First = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        jtxt_1Driver1_Contact = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        jtxt_1CarOwner1_Contact = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jComboBox_1CarBrand1 = new javax.swing.JComboBox<>();
        jLabel23 = new javax.swing.JLabel();
        jComboBox_1CarType1 = new javax.swing.JComboBox<>();
        jtxt_1Car1_PlateNumber = new javax.swing.JTextField();
        jLabel79 = new javax.swing.JLabel();
        jtxt_1Car2_Name = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel80 = new javax.swing.JLabel();
        jtxt_1Car2_PlateNumber = new javax.swing.JTextField();
        jComboBox_1CarBrand2 = new javax.swing.JComboBox<>();
        jLabel29 = new javax.swing.JLabel();
        jComboBox_1CarType2 = new javax.swing.JComboBox<>();
        jLabel30 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        jtxt_1CarOwner2_First = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jtxt_1CarOwner2_Last = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        jtxt_1Driver2_Last = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jtxt_1Driver2_First = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        jtxt_1CarOwner2_Contact = new javax.swing.JTextField();
        jtxt_1Driver2_Contact = new javax.swing.JTextField();
        jLabel40 = new javax.swing.JLabel();
        jbtn_Register = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Josefin Sans", 0, 18)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Branch Agents Supervising");

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel16.setFont(new java.awt.Font("Josefin Sans", 0, 14)); // NOI18N
        jLabel16.setText("Agent#1 Supervises");

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel17.setFont(new java.awt.Font("Josefin Sans", 0, 14)); // NOI18N
        jLabel17.setText("Car #1");

        jtxt_1Car1_Name.setFont(new java.awt.Font("Josefin Sans", 0, 14)); // NOI18N
        jtxt_1Car1_Name.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxt_1Car1_Name.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel18.setFont(new java.awt.Font("Josefin Sans", 0, 14)); // NOI18N
        jLabel18.setText("Car Name:");

        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel19.setFont(new java.awt.Font("Josefin Sans", 0, 14)); // NOI18N
        jLabel19.setText("Car Owner:");

        jtxt_1CarOwner1_First.setFont(new java.awt.Font("Josefin Sans", 0, 14)); // NOI18N
        jtxt_1CarOwner1_First.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxt_1CarOwner1_First.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel20.setFont(new java.awt.Font("Josefin Sans", 0, 14)); // NOI18N
        jLabel20.setText("First Name:");

        jLabel21.setFont(new java.awt.Font("Josefin Sans", 0, 14)); // NOI18N
        jLabel21.setText("Last Name:");

        jtxt_1CarOwner1_Last.setFont(new java.awt.Font("Josefin Sans", 0, 14)); // NOI18N
        jtxt_1CarOwner1_Last.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxt_1CarOwner1_Last.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel25.setFont(new java.awt.Font("Josefin Sans", 0, 14)); // NOI18N
        jLabel25.setText("Driver:");

        jtxt_1Driver1_Last.setFont(new java.awt.Font("Josefin Sans", 0, 14)); // NOI18N
        jtxt_1Driver1_Last.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxt_1Driver1_Last.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel26.setFont(new java.awt.Font("Josefin Sans", 0, 14)); // NOI18N
        jLabel26.setText("Last Name:");

        jLabel27.setFont(new java.awt.Font("Josefin Sans", 0, 14)); // NOI18N
        jLabel27.setText("First Name:");

        jtxt_1Driver1_First.setFont(new java.awt.Font("Josefin Sans", 0, 14)); // NOI18N
        jtxt_1Driver1_First.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxt_1Driver1_First.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel37.setFont(new java.awt.Font("Josefin Sans", 0, 14)); // NOI18N
        jLabel37.setText("Contact Number:");

        jtxt_1Driver1_Contact.setFont(new java.awt.Font("Josefin Sans", 0, 14)); // NOI18N
        jtxt_1Driver1_Contact.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxt_1Driver1_Contact.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel38.setFont(new java.awt.Font("Josefin Sans", 0, 14)); // NOI18N
        jLabel38.setText("Contact Number:");

        jtxt_1CarOwner1_Contact.setFont(new java.awt.Font("Josefin Sans", 0, 14)); // NOI18N
        jtxt_1CarOwner1_Contact.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxt_1CarOwner1_Contact.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addComponent(jLabel19)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel25)
                        .addGap(468, 491, Short.MAX_VALUE))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel27)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtxt_1Driver1_First, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jtxt_1CarOwner1_First, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel26)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtxt_1Driver1_Last)
                        .addContainerGap())
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtxt_1CarOwner1_Last, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel37)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtxt_1Driver1_Contact, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel38)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtxt_1CarOwner1_Contact, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(169, 169, 169))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(jtxt_1CarOwner1_First, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21)
                    .addComponent(jtxt_1CarOwner1_Last, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel38)
                    .addComponent(jtxt_1CarOwner1_Contact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(jtxt_1Driver1_First, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26)
                    .addComponent(jtxt_1Driver1_Last, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel37)
                    .addComponent(jtxt_1Driver1_Contact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jLabel22.setFont(new java.awt.Font("Josefin Sans", 0, 14)); // NOI18N
        jLabel22.setText("Car Brand:");

        jComboBox_1CarBrand1.setFont(new java.awt.Font("Josefin Sans", 0, 14)); // NOI18N
        jComboBox_1CarBrand1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Toyota", "Suzuki", "Nissan", "Mazda", "Mitsubishi", "BMW", "Honda", "Ford" }));

        jLabel23.setFont(new java.awt.Font("Josefin Sans", 0, 14)); // NOI18N
        jLabel23.setText("Car Type:");

        jComboBox_1CarType1.setFont(new java.awt.Font("Josefin Sans", 0, 14)); // NOI18N
        jComboBox_1CarType1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sedan", "Crossover", "SUV", "Hatchback", "Pick-up", "CUV", "Roadster" }));

        jtxt_1Car1_PlateNumber.setFont(new java.awt.Font("Josefin Sans", 0, 14)); // NOI18N
        jtxt_1Car1_PlateNumber.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxt_1Car1_PlateNumber.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel79.setFont(new java.awt.Font("Josefin Sans", 0, 14)); // NOI18N
        jLabel79.setText("Plate Number:");

        jtxt_1Car2_Name.setFont(new java.awt.Font("Josefin Sans", 0, 14)); // NOI18N
        jtxt_1Car2_Name.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxt_1Car2_Name.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel24.setFont(new java.awt.Font("Josefin Sans", 0, 14)); // NOI18N
        jLabel24.setText("Car Name:");

        jLabel28.setFont(new java.awt.Font("Josefin Sans", 0, 14)); // NOI18N
        jLabel28.setText("Car #2");

        jLabel80.setFont(new java.awt.Font("Josefin Sans", 0, 14)); // NOI18N
        jLabel80.setText("Plate Number:");

        jtxt_1Car2_PlateNumber.setFont(new java.awt.Font("Josefin Sans", 0, 14)); // NOI18N
        jtxt_1Car2_PlateNumber.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxt_1Car2_PlateNumber.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jComboBox_1CarBrand2.setFont(new java.awt.Font("Josefin Sans", 0, 14)); // NOI18N
        jComboBox_1CarBrand2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Toyota", "Suzuki", "Nissan", "Mazda", "Mitsubishi", "BMW", "Honda", "Ford" }));

        jLabel29.setFont(new java.awt.Font("Josefin Sans", 0, 14)); // NOI18N
        jLabel29.setText("Car Brand:");

        jComboBox_1CarType2.setFont(new java.awt.Font("Josefin Sans", 0, 14)); // NOI18N
        jComboBox_1CarType2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sedan", "Crossover", "SUV", "Hatchback", "Pick-up", "CUV", "Roadster" }));

        jLabel30.setFont(new java.awt.Font("Josefin Sans", 0, 14)); // NOI18N
        jLabel30.setText("Car Type:");

        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel31.setFont(new java.awt.Font("Josefin Sans", 0, 14)); // NOI18N
        jLabel31.setText("Car Owner:");

        jtxt_1CarOwner2_First.setFont(new java.awt.Font("Josefin Sans", 0, 14)); // NOI18N
        jtxt_1CarOwner2_First.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxt_1CarOwner2_First.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel32.setFont(new java.awt.Font("Josefin Sans", 0, 14)); // NOI18N
        jLabel32.setText("First Name:");

        jLabel33.setFont(new java.awt.Font("Josefin Sans", 0, 14)); // NOI18N
        jLabel33.setText("Last Name:");

        jtxt_1CarOwner2_Last.setFont(new java.awt.Font("Josefin Sans", 0, 14)); // NOI18N
        jtxt_1CarOwner2_Last.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxt_1CarOwner2_Last.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel34.setFont(new java.awt.Font("Josefin Sans", 0, 14)); // NOI18N
        jLabel34.setText("Driver:");

        jtxt_1Driver2_Last.setFont(new java.awt.Font("Josefin Sans", 0, 14)); // NOI18N
        jtxt_1Driver2_Last.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxt_1Driver2_Last.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel35.setFont(new java.awt.Font("Josefin Sans", 0, 14)); // NOI18N
        jLabel35.setText("Last Name:");

        jLabel36.setFont(new java.awt.Font("Josefin Sans", 0, 14)); // NOI18N
        jLabel36.setText("First Name:");

        jtxt_1Driver2_First.setFont(new java.awt.Font("Josefin Sans", 0, 14)); // NOI18N
        jtxt_1Driver2_First.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxt_1Driver2_First.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel39.setFont(new java.awt.Font("Josefin Sans", 0, 14)); // NOI18N
        jLabel39.setText("Contact Number:");

        jtxt_1CarOwner2_Contact.setFont(new java.awt.Font("Josefin Sans", 0, 14)); // NOI18N
        jtxt_1CarOwner2_Contact.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxt_1CarOwner2_Contact.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jtxt_1Driver2_Contact.setFont(new java.awt.Font("Josefin Sans", 0, 14)); // NOI18N
        jtxt_1Driver2_Contact.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxt_1Driver2_Contact.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel40.setFont(new java.awt.Font("Josefin Sans", 0, 14)); // NOI18N
        jLabel40.setText("Contact Number:");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addComponent(jLabel31)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel34)
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(jLabel36)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtxt_1Driver2_First, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel35)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtxt_1Driver2_Last, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel32)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtxt_1CarOwner2_First, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel33)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtxt_1CarOwner2_Last, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addGap(121, 121, 121)
                                .addComponent(jLabel39)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtxt_1CarOwner2_Contact, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addGap(123, 123, 123)
                                .addComponent(jLabel40)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtxt_1Driver2_Contact, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addComponent(jLabel31)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32)
                    .addComponent(jtxt_1CarOwner2_First, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel33)
                    .addComponent(jtxt_1CarOwner2_Last, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel39)
                    .addComponent(jtxt_1CarOwner2_Contact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(jLabel34)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel36)
                    .addComponent(jtxt_1Driver2_First, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel35)
                    .addComponent(jtxt_1Driver2_Last, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel40)
                    .addComponent(jtxt_1Driver2_Contact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel9Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel17)
                        .addGroup(jPanel9Layout.createSequentialGroup()
                            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel9Layout.createSequentialGroup()
                                    .addGap(22, 22, 22)
                                    .addComponent(jLabel18)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jtxt_1Car1_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel79))
                                .addGroup(jPanel9Layout.createSequentialGroup()
                                    .addGap(28, 28, 28)
                                    .addComponent(jLabel23)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jComboBox_1CarType1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel22)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jComboBox_1CarBrand1, 0, 174, Short.MAX_VALUE)
                                .addComponent(jtxt_1Car1_PlateNumber)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel28)
                        .addGroup(jPanel9Layout.createSequentialGroup()
                            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel9Layout.createSequentialGroup()
                                    .addGap(22, 22, 22)
                                    .addComponent(jLabel24)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jtxt_1Car2_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel80))
                                .addGroup(jPanel9Layout.createSequentialGroup()
                                    .addGap(28, 28, 28)
                                    .addComponent(jLabel30)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jComboBox_1CarType2, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel29)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jComboBox_1CarBrand2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jtxt_1Car2_PlateNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel28)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel24)
                            .addComponent(jtxt_1Car2_Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel80)
                            .addComponent(jtxt_1Car2_PlateNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox_1CarType2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel30)
                            .addComponent(jComboBox_1CarBrand2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel29))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(jtxt_1Car1_Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel79)
                            .addComponent(jtxt_1Car1_PlateNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox_1CarType1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel23)
                            .addComponent(jComboBox_1CarBrand1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel22))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jbtn_Register.setBackground(new java.awt.Color(0, 0, 0));
        jbtn_Register.setFont(new java.awt.Font("Josefin Sans", 0, 18)); // NOI18N
        jbtn_Register.setForeground(new java.awt.Color(255, 255, 255));
        jbtn_Register.setText("Register Cars");
        jbtn_Register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_RegisterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel16))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(477, 477, 477)
                        .addComponent(jbtn_Register, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(626, 626, 626))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbtn_Register, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(273, 273, 273))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 1250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel15)
                .addGap(507, 507, 507))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 509, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        HomePageUI homeUI = new HomePageUI(accountID);
        homeUI.setVisible(true);
    }//GEN-LAST:event_formWindowClosed

    private void jbtn_RegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_RegisterActionPerformed
        register();
    }//GEN-LAST:event_jbtn_RegisterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CarRentalUI_AgentDetails1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CarRentalUI_AgentDetails1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CarRentalUI_AgentDetails1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CarRentalUI_AgentDetails1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CarRentalUI_AgentDetails1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox_1CarBrand1;
    private javax.swing.JComboBox<String> jComboBox_1CarBrand2;
    private javax.swing.JComboBox<String> jComboBox_1CarType1;
    private javax.swing.JComboBox<String> jComboBox_1CarType2;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel79;
    private javax.swing.JLabel jLabel80;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JButton jbtn_Register;
    private javax.swing.JTextField jtxt_1Car1_Name;
    private javax.swing.JTextField jtxt_1Car1_PlateNumber;
    private javax.swing.JTextField jtxt_1Car2_Name;
    private javax.swing.JTextField jtxt_1Car2_PlateNumber;
    private javax.swing.JTextField jtxt_1CarOwner1_Contact;
    private javax.swing.JTextField jtxt_1CarOwner1_First;
    private javax.swing.JTextField jtxt_1CarOwner1_Last;
    private javax.swing.JTextField jtxt_1CarOwner2_Contact;
    private javax.swing.JTextField jtxt_1CarOwner2_First;
    private javax.swing.JTextField jtxt_1CarOwner2_Last;
    private javax.swing.JTextField jtxt_1Driver1_Contact;
    private javax.swing.JTextField jtxt_1Driver1_First;
    private javax.swing.JTextField jtxt_1Driver1_Last;
    private javax.swing.JTextField jtxt_1Driver2_Contact;
    private javax.swing.JTextField jtxt_1Driver2_First;
    private javax.swing.JTextField jtxt_1Driver2_Last;
    // End of variables declaration//GEN-END:variables

    private void register(){
        try{
            String agentFirst = agents.get(0).getFirstName();
            String agentLast = agents.get(0).getLastName();
            String agentName = String.format("%s %s",agentFirst,agentLast);
            int agentID = agentDAO.getAgentID(agentName);
            int branchID = branchDAO.getBranchID(theBranch.getBranchName());
            
            System.out.println(agentID + ": " + agentName);
            
            String aCar1Name = jtxt_1Car1_Name.getText().trim();
            String aCar1Plate = jtxt_1Car1_PlateNumber.getText().trim();
            String aCar1Brand = jComboBox_1CarBrand1.getSelectedItem().toString();
            String aCar1Type = jComboBox_1CarType1.getSelectedItem().toString();
            String aCarOwner1First = jtxt_1CarOwner1_First.getText().trim();
            String aCarOwner1Last = jtxt_1CarOwner1_Last.getText().trim();
            String aCarOwner1Contact = jtxt_1CarOwner1_Contact.getText().trim();
            String aCarDriver1First = jtxt_1Driver1_First.getText().trim();
            String aCarDriver1Last = jtxt_1Driver1_Last.getText().trim();
            String aCarDriver1Contact = jtxt_1Driver1_Contact.getText().trim();
            
            String aCar2Name = jtxt_1Car2_Name.getText().trim();
            String aCar2Plate = jtxt_1Car2_PlateNumber.getText().trim();
            String aCar2Brand = jComboBox_1CarBrand2.getSelectedItem().toString();
            String aCar2Type = jComboBox_1CarType2.getSelectedItem().toString();
            String aCarOwner2First = jtxt_1CarOwner2_First.getText().trim();
            String aCarOwner2Last = jtxt_1CarOwner2_Last.getText().trim();
            String aCarOwner2Contact = jtxt_1CarOwner2_Contact.getText().trim();
            String aCarDriver2First = jtxt_1Driver2_First.getText().trim();
            String aCarDriver2Last = jtxt_1Driver2_Last.getText().trim();
            String aCarDriver2Contact = jtxt_1Driver2_Contact.getText().trim();
            
            ArrayList<Car> cars = new ArrayList<>();
            ArrayList<CarOwner> owners = new ArrayList<>();
            ArrayList<Driver> drivers = new ArrayList<>();
            
            /* Encapsulate all Agent #1: Car #1 Details */
            
            if(!(aCar1Name.isEmpty()) && !(aCarOwner1First.isEmpty())){
                String ownerName = String.format("%s %s",aCarOwner1First,aCarOwner1Last);
                
                Car car = new Car(aCar1Name,ownerName,aCar1Brand,aCar1Type,aCar1Plate);
                CarOwner owner = new CarOwner(theBranch.getBranchName(),agentName,aCarOwner1First,aCarOwner1Last,aCarOwner1Contact);
                owner.setAgentID(agentID);
                owner.setBranchID(branchID);
                Driver driver = new Driver(theBranch.getBranchName(),agentName,aCar1Name,aCarDriver1First,aCarDriver1Last,aCarDriver1Contact);
                driver.setAgentID(agentID);
                driver.setBranchID(branchID);
                
                cars.add(car);
                owners.add(owner);
                drivers.add(driver);
            }
            
            /* Encapsulate all Agent #1: Car #2 Details */
            
            if(!(aCar2Name.isEmpty()) && !(aCarOwner2First.isEmpty())){
                String ownerName = String.format("%s %s",aCarOwner2First,aCarOwner2Last);
                
                Car car = new Car(aCar2Name,ownerName,aCar2Brand,aCar2Type,aCar2Plate);
                CarOwner owner = new CarOwner(theBranch.getBranchName(),agentName,aCarOwner2First,aCarOwner2Last,aCarOwner2Contact);
                owner.setAgentID(agentID);
                owner.setBranchID(branchID);
                Driver driver = new Driver(theBranch.getBranchName(),agentName,aCar2Name,aCarDriver2First,aCarDriver2Last,aCarDriver2Contact);
                driver.setAgentID(agentID);
                driver.setBranchID(branchID);
                
                cars.add(car);
                owners.add(owner);
                drivers.add(driver);
            }
            else if((!(aCar1Name.isEmpty()) && aCarOwner1First.isEmpty()) || 
                        (!(aCar2Name.isEmpty()) && aCarOwner2First.isEmpty())){
                JOptionPane.showMessageDialog(CarRentalUI_AgentDetails1.this,"A car must have an owner!","Register Error",JOptionPane.ERROR_MESSAGE);
            }
            
            for(int i = 0;i<owners.size();i++){
                String ownerName = String.format("%s %s",owners.get(i).getOwnerFirstName(),owners.get(i).getOwnerLastName());
                if(ownerDAO.checkIfOwner(ownerName)){
                    int ownerID = ownerDAO.getCarOwnerID(ownerName);
                    int carsOwned = ownerDAO.getOwnedCars(ownerName);
                    
                    ownerDAO.updateCarsOwned(ownerID,carsOwned + 1);
                }
                else{
                    CarOwner newOwner = owners.get(i);
                    newOwner.setOwnedCrs(1);
                    ownerDAO.AddCarOwner(newOwner);
                }
                
                
                String name = String.format("%s %s",owners.get(i).getOwnerFirstName(),owners.get(i).getOwnerLastName());
                int ownerID = ownerDAO.getCarOwnerID(name);
                cars.get(i).setOwnerID(ownerID);
                
                carDAO.RegisterNewCar(cars.get(i));
                
                int carID = carDAO.getCarID(cars.get(i).getCarName());
                drivers.get(i).setCarID(carID);
                
                driverDAO.EmployDriver(drivers.get(i));
            }
            
            int totalcars = cars.size();
            int totalowners = owners.size();
            int totaldrivers = drivers.size();
            
            JOptionPane.showMessageDialog(CarRentalUI_AgentDetails1.this,
                    "Branch: " + theBranch.getBranchName() + "\n"
                  + "Manager: " + theBranch.getBranchManagerFirst() + " " + theBranch.getBranchManagerLast() + "\n"
                  + "\tAgents: 1\n"
                  + "\tName: " + agents.get(0).getFirstName() + " " + agents.get(0).getLastName() + "\n"
                  + "\tSupervised Cars: " + totalcars + "\n"
                  + "\tSupervised Car Owners: " + totalowners + "\n"
                  + "\tSupervised Drivers: " + totaldrivers + "\n\n"
                          + "Branch has been registered successfully!","Register Success",JOptionPane.INFORMATION_MESSAGE);
            HomePageUI home = new HomePageUI(accountID);
            setVisible(false);
            home.setVisible(true);
        }
        catch(Exception exc){
            exc.printStackTrace();
        }
    }
}
