/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mysql.gui;

import javax.swing.JOptionPane;

/**
 *
 * @author Jur Yel
 */
import mysql.core.Branch;
import mysql.dao.BranchDAO;
import mysql.core.Agent;
import mysql.dao.AgentDAO;
import mysql.core.Manager;
import mysql.dao.ManagerDAO;
import java.util.ArrayList;

public class CarRentalUI_AddBranch extends javax.swing.JFrame {

    /**
     * Creates new form CarRentalUI_AddBranch
     */
    private BranchDAO branchDAO;
    private ManagerDAO mngrDAO;
    private AgentDAO agentDAO;
    private String accountID;
    
    public CarRentalUI_AddBranch(String accID) {
        try{
            branchDAO = new BranchDAO();
            mngrDAO = new ManagerDAO();
            agentDAO = new AgentDAO();
            
        }
        catch(Exception exc){
            exc.printStackTrace();
        }
        initComponents();
        setLocationRelativeTo(null);
        accountID = accID;
        
    }
    
    public CarRentalUI_AddBranch(){
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jtxt_Branch = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jtxt_BranchFirst = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtxt_BranchLast = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jlblLabel = new javax.swing.JLabel();
        jtxt_BranchContactNumber = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jtxt_Agent2_First = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jtxt_Agent2_Last = new javax.swing.JTextField();
        jtxt_Agent2_Contact = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jtxt_Agent1_First = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jtxt_Agent1_Last = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jtxt_Agent1_Contact = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jtxt_Agent3_First = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jtxt_Agent3_Last = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jtxt_Agent3_Contact = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jbtn_Register = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel2.setFont(new java.awt.Font("Josefin Sans", 0, 18)); // NOI18N
        jLabel2.setText("Branch Manager:");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jtxt_Branch.setFont(new java.awt.Font("Josefin Sans", 0, 18)); // NOI18N
        jtxt_Branch.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxt_Branch.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel1.setFont(new java.awt.Font("Josefin Sans", 0, 18)); // NOI18N
        jLabel1.setText("Branch:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jtxt_Branch, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxt_Branch, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jtxt_BranchFirst.setFont(new java.awt.Font("Josefin Sans", 0, 14)); // NOI18N
        jtxt_BranchFirst.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxt_BranchFirst.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel3.setFont(new java.awt.Font("Josefin Sans", 0, 14)); // NOI18N
        jLabel3.setText("First Name:");

        jtxt_BranchLast.setFont(new java.awt.Font("Josefin Sans", 0, 14)); // NOI18N
        jtxt_BranchLast.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxt_BranchLast.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel4.setFont(new java.awt.Font("Josefin Sans", 0, 14)); // NOI18N
        jLabel4.setText("Last Name:");

        jlblLabel.setFont(new java.awt.Font("Josefin Sans", 0, 14)); // NOI18N
        jlblLabel.setText("Contact Number:");

        jtxt_BranchContactNumber.setFont(new java.awt.Font("Josefin Sans", 0, 14)); // NOI18N
        jtxt_BranchContactNumber.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxt_BranchContactNumber.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtxt_BranchFirst, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtxt_BranchLast, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jlblLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtxt_BranchContactNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxt_BranchFirst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxt_BranchLast, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxt_BranchContactNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblLabel))
                .addContainerGap(7, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel6.setFont(new java.awt.Font("Josefin Sans", 0, 14)); // NOI18N
        jLabel6.setText("Agent #2:");

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel7.setFont(new java.awt.Font("Josefin Sans", 0, 14)); // NOI18N
        jLabel7.setText("First Name:");

        jtxt_Agent2_First.setFont(new java.awt.Font("Josefin Sans", 0, 14)); // NOI18N
        jtxt_Agent2_First.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxt_Agent2_First.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel8.setFont(new java.awt.Font("Josefin Sans", 0, 14)); // NOI18N
        jLabel8.setText("Last Name:");

        jtxt_Agent2_Last.setFont(new java.awt.Font("Josefin Sans", 0, 14)); // NOI18N
        jtxt_Agent2_Last.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxt_Agent2_Last.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jtxt_Agent2_Contact.setFont(new java.awt.Font("Josefin Sans", 0, 14)); // NOI18N
        jtxt_Agent2_Contact.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxt_Agent2_Contact.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel16.setFont(new java.awt.Font("Josefin Sans", 0, 14)); // NOI18N
        jLabel16.setText("Contact Number:");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtxt_Agent2_Contact, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                            .addComponent(jtxt_Agent2_Last)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtxt_Agent2_First, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jtxt_Agent2_First, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jtxt_Agent2_Last, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jtxt_Agent2_Contact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel9.setFont(new java.awt.Font("Josefin Sans", 0, 14)); // NOI18N
        jLabel9.setText("Agent #1:");

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel10.setFont(new java.awt.Font("Josefin Sans", 0, 14)); // NOI18N
        jLabel10.setText("First Name:");

        jtxt_Agent1_First.setFont(new java.awt.Font("Josefin Sans", 0, 14)); // NOI18N
        jtxt_Agent1_First.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxt_Agent1_First.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel11.setFont(new java.awt.Font("Josefin Sans", 0, 14)); // NOI18N
        jLabel11.setText("Last Name:");

        jtxt_Agent1_Last.setFont(new java.awt.Font("Josefin Sans", 0, 14)); // NOI18N
        jtxt_Agent1_Last.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxt_Agent1_Last.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel15.setFont(new java.awt.Font("Josefin Sans", 0, 14)); // NOI18N
        jLabel15.setText("Contact Number:");

        jtxt_Agent1_Contact.setFont(new java.awt.Font("Josefin Sans", 0, 14)); // NOI18N
        jtxt_Agent1_Contact.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxt_Agent1_Contact.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel6Layout.createSequentialGroup()
                            .addComponent(jLabel10)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jtxt_Agent1_First, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel6Layout.createSequentialGroup()
                            .addComponent(jLabel11)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jtxt_Agent1_Last, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtxt_Agent1_Contact, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jtxt_Agent1_First, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jtxt_Agent1_Last, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jtxt_Agent1_Contact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel12.setFont(new java.awt.Font("Josefin Sans", 0, 14)); // NOI18N
        jLabel12.setText("Agent #3:");

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel13.setFont(new java.awt.Font("Josefin Sans", 0, 14)); // NOI18N
        jLabel13.setText("First Name:");

        jtxt_Agent3_First.setFont(new java.awt.Font("Josefin Sans", 0, 14)); // NOI18N
        jtxt_Agent3_First.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxt_Agent3_First.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel14.setFont(new java.awt.Font("Josefin Sans", 0, 14)); // NOI18N
        jLabel14.setText("Last Name:");

        jtxt_Agent3_Last.setFont(new java.awt.Font("Josefin Sans", 0, 14)); // NOI18N
        jtxt_Agent3_Last.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxt_Agent3_Last.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel17.setFont(new java.awt.Font("Josefin Sans", 0, 14)); // NOI18N
        jLabel17.setText("Contact Number:");

        jtxt_Agent3_Contact.setFont(new java.awt.Font("Josefin Sans", 0, 14)); // NOI18N
        jtxt_Agent3_Contact.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxt_Agent3_Contact.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtxt_Agent3_First, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtxt_Agent3_Last, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtxt_Agent3_Contact)))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jtxt_Agent3_First, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jtxt_Agent3_Last, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jtxt_Agent3_Contact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel9)
                    .addComponent(jLabel6)
                    .addComponent(jLabel12)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel5.setFont(new java.awt.Font("Josefin Sans", 0, 18)); // NOI18N
        jLabel5.setText("Branch Agents");

        jbtn_Register.setBackground(new java.awt.Color(0, 0, 0));
        jbtn_Register.setFont(new java.awt.Font("Josefin Sans", 0, 18)); // NOI18N
        jbtn_Register.setForeground(new java.awt.Color(255, 255, 255));
        jbtn_Register.setText("Register Branch");
        jbtn_Register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_RegisterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel2))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jbtn_Register, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(12, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addGap(119, 119, 119))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbtn_Register, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        HomePageUI homeUI = new HomePageUI(accountID);
        homeUI.setVisible(true);
    }//GEN-LAST:event_formWindowClosed

    private void jbtn_RegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_RegisterActionPerformed
        register();
    }//GEN-LAST:event_jbtn_RegisterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CarRentalUI_AddBranch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CarRentalUI_AddBranch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CarRentalUI_AddBranch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CarRentalUI_AddBranch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CarRentalUI_AddBranch().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JButton jbtn_Register;
    private javax.swing.JLabel jlblLabel;
    private javax.swing.JTextField jtxt_Agent1_Contact;
    private javax.swing.JTextField jtxt_Agent1_First;
    private javax.swing.JTextField jtxt_Agent1_Last;
    private javax.swing.JTextField jtxt_Agent2_Contact;
    private javax.swing.JTextField jtxt_Agent2_First;
    private javax.swing.JTextField jtxt_Agent2_Last;
    private javax.swing.JTextField jtxt_Agent3_Contact;
    private javax.swing.JTextField jtxt_Agent3_First;
    private javax.swing.JTextField jtxt_Agent3_Last;
    private javax.swing.JTextField jtxt_Branch;
    private javax.swing.JTextField jtxt_BranchContactNumber;
    private javax.swing.JTextField jtxt_BranchFirst;
    private javax.swing.JTextField jtxt_BranchLast;
    // End of variables declaration//GEN-END:variables

    private void register(){
        try{
            String branch = jtxt_Branch.getText().trim();
            String mngr_first = jtxt_BranchFirst.getText().trim();
            String mngr_last = jtxt_BranchLast.getText().trim();
            String mngr_contact = jtxt_BranchContactNumber.getText().trim();
            String agent1_first = jtxt_Agent1_First.getText().trim();
            String agent1_last = jtxt_Agent1_Last.getText().trim();
            String agent1_contact = jtxt_Agent1_Contact.getText().trim();
            String agent2_first = jtxt_Agent2_First.getText().trim();
            String agent2_last = jtxt_Agent2_Last.getText().trim();
            String agent2_contact = jtxt_Agent2_Contact.getText().trim();
            String agent3_first = jtxt_Agent3_First.getText().trim();
            String agent3_last = jtxt_Agent3_Last.getText().trim();
            String agent3_contact = jtxt_Agent3_Contact.getText().trim();
            
            if(branch.isEmpty() || mngr_first.isEmpty() || mngr_last.isEmpty()){
                JOptionPane.showMessageDialog(CarRentalUI_AddBranch.this,"Branch and Branch Manager can not be empty!","Register Error",JOptionPane.ERROR_MESSAGE);
            }
            else{
                if(branchDAO.checkIfBranchExists(branch)){
                    JOptionPane.showMessageDialog(CarRentalUI_AddBranch.this,"Branch already exists!","Register Error",JOptionPane.ERROR_MESSAGE);
                }
                else{
                    String exbranch = branchDAO.getBranchByManager(mngr_first + " " + mngr_last);
                    if(branchDAO.checkIfManager(mngr_first + " " + mngr_last)){
                        JOptionPane.showMessageDialog(CarRentalUI_AddBranch.this,mngr_first + " " + mngr_last + " is already the manger of " + exbranch + "!",
                                                        "Register Error",JOptionPane.ERROR_MESSAGE);
                    }
                    else{
                        String agent1 = String.format("%s %s",agent1_first,agent1_last);
                        String agent2 = String.format("%s %s",agent2_first,agent2_last);
                        String agent3 = String.format("%s %s",agent3_first,agent3_last);
                        
                        if(agent1.isEmpty() && agent2.isEmpty() && agent3.isEmpty()){
                            JOptionPane.showMessageDialog(CarRentalUI_AddBranch.this,"Branch must have at least 1 agent!","Register Error",JOptionPane.ERROR_MESSAGE);
                        }
                        else{
                            if(agentDAO.checkIfAgent(agent1) || 
                                agentDAO.checkIfAgent(agent2) ||
                                agentDAO.checkIfAgent(agent3)){
                                if(agentDAO.checkIfAgent(agent1)){
                                    String agBranch = agentDAO.getBranchByAgent(agent1);
                                    JOptionPane.showMessageDialog(CarRentalUI_AddBranch.this,agent1 + " is already an agent of " + agBranch + "!","Register Error",JOptionPane.ERROR_MESSAGE);
                                }
                                if(agentDAO.checkIfAgent(agent2)){
                                    String agBranch = agentDAO.getBranchByAgent(agent2);
                                    JOptionPane.showMessageDialog(CarRentalUI_AddBranch.this,agent2 + " is already an agent of " + agBranch + "!","Register Error",JOptionPane.ERROR_MESSAGE);
                                }
                                if(agentDAO.checkIfAgent(agent3)){
                                    String agBranch = agentDAO.getBranchByAgent(agent3);
                                    JOptionPane.showMessageDialog(CarRentalUI_AddBranch.this,agent2 + " is already an agent of " + agBranch + "!","Register Error",JOptionPane.ERROR_MESSAGE);
                                }
                            }
                            else{
                                
                                Branch newBranch = new Branch(branch,mngr_first,mngr_last,mngr_contact);
                                ArrayList<Agent> agents = new ArrayList<>();
                                
                                branchDAO.AddNewBranch(newBranch);
                                int branchID = branchDAO.getBranchID(branch);
                                
                                if(!(agent1_first.isEmpty())){
                                    Agent newAgent1 = new Agent(branch,agent1_first,agent1_last,agent1_contact);
                                    agentDAO.AddNewAgent(newAgent1, branchID);
                                    agents.add(newAgent1);
                                }
                                if(!(agent2_first.isEmpty())){
                                    Agent newAgent2 = new Agent(branch,agent2_first,agent2_last,agent2_contact);
                                    agentDAO.AddNewAgent(newAgent2, branchID);
                                    agents.add(newAgent2);
                                }
                                if(!(agent3_first.isEmpty())){
                                    Agent newAgent3 = new Agent(branch,agent3_first,agent3_last,agent3_contact);
                                    agentDAO.AddNewAgent(newAgent3, branchID);
                                    agents.add(newAgent3);
                                }
                                
                                int totalAgents = agents.size();
                                
                                switch(totalAgents){
                                    case 1:
                                        CarRentalUI_AgentDetails1 agent1UI = new CarRentalUI_AgentDetails1(newBranch,agents,accountID);
                                        setVisible(false);
                                        agent1UI.setVisible(true);
                                        break;
                                    case 2:
                                        CarRentalUI_AgentDetails2 agent2UI = new CarRentalUI_AgentDetails2(newBranch,agents,accountID);
                                        setVisible(false);
                                        agent2UI.setVisible(true);
                                        break;
                                    case 3:
                                        CarRentalUI_AgentDetails3 agent3UI = new CarRentalUI_AgentDetails3(newBranch,agents,accountID);
                                        setVisible(false);
                                        agent3UI.setVisible(true);
                                        break;
                                }
                            }
                            
                        }
                    }
                }
            }
        }
        catch(Exception exc){
            exc.printStackTrace();
        }
    }
}
