/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mysql.gui;

/**
 *
 * @author Jur Yel
 */
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import mysql.core.Agent;
import mysql.core.Branch;
import mysql.core.Car;
import mysql.core.Driver;
import mysql.dao.BranchDAO;
import mysql.dao.AgentDAO;
import mysql.dao.CarDAO;
import mysql.dao.DriverDAO;
import mysql.dao.BookingsDAO;

public class DriverUI extends javax.swing.JFrame {

    /**
     * Creates new form DriverUI
     */
    private BranchDAO branchDAO;
    private AgentDAO agentDAO;
    private CarDAO carDAO;
    private DriverDAO driverDAO;
    private BookingsDAO bookDAO;
    private String accountID;
    
    public DriverUI(String accID) {
        try{
            bookDAO = new BookingsDAO();
            branchDAO = new BranchDAO();
            agentDAO = new AgentDAO();
            carDAO = new CarDAO();
            driverDAO = new DriverDAO();
        }
        catch(Exception exc){
            exc.printStackTrace();
        }
        initComponents();
        setLocationRelativeTo(null);
        populateTable();
        populateGUI();
        accountID = accID;
    }
    
    public DriverUI(){
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox_Branch = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jComboBox_Agent = new javax.swing.JComboBox<>();
        jComboBox_Car = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jtxt_First = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jtxt_Last = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jtxt_Contact = new javax.swing.JTextField();
        jbtn_Register = new javax.swing.JButton();
        jbtn_Update = new javax.swing.JButton();
        jbtn_Expel = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jtxt_Search = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbl_Drivers = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel1.setFont(new java.awt.Font("Bebas Neue", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("D R I V E R  D E T A I L S");

        jLabel2.setFont(new java.awt.Font("Josefin Sans", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Branch:");

        jComboBox_Branch.setFont(new java.awt.Font("Josefin Sans", 0, 14)); // NOI18N
        jComboBox_Branch.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jComboBox_Branch.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox_BranchItemStateChanged(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Josefin Sans", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Agent:");

        jComboBox_Agent.setFont(new java.awt.Font("Josefin Sans", 0, 14)); // NOI18N
        jComboBox_Agent.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jComboBox_Car.setFont(new java.awt.Font("Josefin Sans", 0, 14)); // NOI18N
        jComboBox_Car.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel4.setFont(new java.awt.Font("Josefin Sans", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Car:");

        jtxt_First.setFont(new java.awt.Font("Josefin Sans", 0, 14)); // NOI18N
        jtxt_First.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxt_First.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel5.setFont(new java.awt.Font("Josefin Sans", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("First Name:");

        jLabel6.setFont(new java.awt.Font("Josefin Sans", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Last Name:");

        jtxt_Last.setFont(new java.awt.Font("Josefin Sans", 0, 14)); // NOI18N
        jtxt_Last.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxt_Last.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel7.setFont(new java.awt.Font("Josefin Sans", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Contact Number:");

        jtxt_Contact.setFont(new java.awt.Font("Josefin Sans", 0, 14)); // NOI18N
        jtxt_Contact.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxt_Contact.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jComboBox_Agent, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jComboBox_Branch, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jtxt_First)
                                    .addComponent(jComboBox_Car, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jtxt_Last)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(12, 12, 12)
                        .addComponent(jtxt_Contact, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(84, 84, 84))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBox_Branch, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jComboBox_Agent, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jComboBox_Car, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxt_First, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxt_Last, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxt_Contact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)))
        );

        jbtn_Register.setBackground(new java.awt.Color(153, 153, 153));
        jbtn_Register.setFont(new java.awt.Font("Josefin Sans", 0, 14)); // NOI18N
        jbtn_Register.setText("Register Driver");
        jbtn_Register.setToolTipText("");
        jbtn_Register.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtn_Register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_RegisterActionPerformed(evt);
            }
        });

        jbtn_Update.setBackground(new java.awt.Color(153, 153, 153));
        jbtn_Update.setFont(new java.awt.Font("Josefin Sans", 0, 14)); // NOI18N
        jbtn_Update.setText("Update Driver");
        jbtn_Update.setToolTipText("");
        jbtn_Update.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtn_Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_UpdateActionPerformed(evt);
            }
        });

        jbtn_Expel.setBackground(new java.awt.Color(153, 153, 153));
        jbtn_Expel.setFont(new java.awt.Font("Josefin Sans", 0, 14)); // NOI18N
        jbtn_Expel.setText("Expel Driver");
        jbtn_Expel.setToolTipText("");
        jbtn_Expel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtn_Expel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_ExpelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(117, Short.MAX_VALUE)
                .addComponent(jbtn_Register)
                .addGap(106, 106, 106))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jbtn_Update, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbtn_Expel, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtn_Register, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtn_Update, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn_Expel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 92, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, -1, 554));

        jPanel4.setBackground(new java.awt.Color(102, 102, 102));

        jtxt_Search.setFont(new java.awt.Font("Josefin Sans", 0, 14)); // NOI18N
        jtxt_Search.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxt_Search.setText("Search Driver...");
        jtxt_Search.setToolTipText("");
        jtxt_Search.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jtxt_Search.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jtxt_SearchMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jtxt_SearchMouseExited(evt);
            }
        });
        jtxt_Search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxt_SearchKeyTyped(evt);
            }
        });

        jtbl_Drivers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtbl_Drivers.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jtbl_Drivers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtbl_DriversMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtbl_Drivers);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 938, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jtxt_Search, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(333, 333, 333))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jtxt_Search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1))
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(345, 70, -1, 555));

        jLabel8.setFont(new java.awt.Font("Bebas Neue", 0, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("R E G I S T E R E D  D R I V E R S");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 14, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ico/icons8_home_page_30px.png"))); // NOI18N
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtn_RegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_RegisterActionPerformed
        try{
            String branch = jComboBox_Branch.getSelectedItem().toString();
            String agent = jComboBox_Agent.getSelectedItem().toString();
            String car = jComboBox_Car.getSelectedItem().toString();
            String first = jtxt_First.getText().trim();
            String last = jtxt_Last.getText().trim();
            String contact = jtxt_Contact.getText().trim();
            
            if(first.isEmpty() || contact.isEmpty()){
                JOptionPane.showMessageDialog(DriverUI.this,"Fill up all fields!","Register Error",JOptionPane.ERROR_MESSAGE);
            }
            else{
                int branchID = branchDAO.getBranchID(branch);
                int agentID = agentDAO.getAgentID(agent);
                int carID = carDAO.getCarID(car);
                
                if(driverDAO.checkIfDriver(first + " " + last)){
                    String carDrived = driverDAO.getCarDrived(String.format("%s %s",first,last));
                    JOptionPane.showMessageDialog(DriverUI.this,first + " " + last + " is already a driver of " + carDrived+ "!","Register Error",JOptionPane.ERROR_MESSAGE);
                }
                else{
                    Driver driver = new Driver(branch,agent,car,first,last,contact);
                    driver.setBranchID(branchID);
                    driver.setAgentID(agentID);
                    driver.setCarID(carID);

                    driverDAO.EmployDriver(driver);
                    JOptionPane.showMessageDialog(DriverUI.this,"Driver registered successfully!","Register Success",JOptionPane.INFORMATION_MESSAGE);
                    populateTable();
                    reset();
                }
                
            }
        }
        catch(Exception exc){
            exc.printStackTrace();
        }
    }//GEN-LAST:event_jbtn_RegisterActionPerformed

    private void jbtn_UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_UpdateActionPerformed
        int row = jtbl_Drivers.getSelectedRow();
        if(row < 0){
            JOptionPane.showMessageDialog(DriverUI.this,"Select a row","Update Error",JOptionPane.ERROR_MESSAGE);
        }
        else{
            try{
                String branch = jComboBox_Branch.getSelectedItem().toString();
                String agent = jComboBox_Agent.getSelectedItem().toString();
                String car = jComboBox_Car.getSelectedItem().toString();
                String carRec = jtbl_Drivers.getValueAt(row,2).toString();
                String first = jtxt_First.getText().trim();
                String last = jtxt_Last.getText().trim();
                String contact = jtxt_Contact.getText().trim();

                int branchID = branchDAO.getBranchID(branch);
                    int agentID = agentDAO.getAgentID(agent);
                    int carID = carDAO.getCarID(car);

                    if(driverDAO.checkIfDriver(first + " " + last)){
                        String carDrived = driverDAO.getCarDrived(String.format("%s %s",first,last));
                        JOptionPane.showMessageDialog(DriverUI.this,first + " " + last + " is already a driver of " + carDrived+ "!","Register Error",JOptionPane.ERROR_MESSAGE);
                    }
                    else{
                        if(car.equals(carRec)){
                            Driver driver = new Driver(branch,agent,car,first,last,contact);
                            driver.setBranchID(branchID);
                            driver.setAgentID(agentID);
                            driver.setCarID(carID);

                            driverDAO.UpdateDriver(driver);
                            JOptionPane.showMessageDialog(DriverUI.this,"Driver updated successfully!","Update Success",JOptionPane.INFORMATION_MESSAGE);
                            populateTable();
                            reset();
                        }
                        else{
                            if(driverDAO.checkIfCarHasDriver(carID)){
                                JOptionPane.showMessageDialog(DriverUI.this,"Car already has a driver!","Update Error",JOptionPane.ERROR_MESSAGE);
                            }
                            else{
                                Driver driver = new Driver(branch,agent,car,first,last,contact);
                                driver.setBranchID(branchID);
                                driver.setAgentID(agentID);
                                driver.setCarID(carID);

                                driverDAO.UpdateDriver(driver);
                                JOptionPane.showMessageDialog(DriverUI.this,"Driver updated successfully!","Update Success",JOptionPane.INFORMATION_MESSAGE);
                                populateTable();
                                reset();
                            }
                        }
                    }
            }
            catch(Exception exc){
                exc.printStackTrace();
            }
        }
        
    }//GEN-LAST:event_jbtn_UpdateActionPerformed

    private void jbtn_ExpelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_ExpelActionPerformed
        int row = jtbl_Drivers.getSelectedRow();
        if(row < 0){
            JOptionPane.showMessageDialog(DriverUI.this,"Select a row","Expel Error",JOptionPane.ERROR_MESSAGE);
        }
        else{
            try{
                String first = jtxt_First.getText().trim();
                String last = jtxt_Last.getText().trim();
                int driverID = driverDAO.getDriverID(first + " " + last);

                String car = driverDAO.getCarDrived(first + " " + last);

                if((JOptionPane.showConfirmDialog(DriverUI.this,first + " " + last + " is the driver of " + car + "\n"
                        + "Are you sure to expel driver?","Confirm Expulsion",JOptionPane.YES_NO_OPTION,JOptionPane.WARNING_MESSAGE)) == JOptionPane.YES_OPTION){
                    driverDAO.FireDriver(driverID);

                    JOptionPane.showMessageDialog(DriverUI.this,"Driver has been expelled","Expel Success",JOptionPane.INFORMATION_MESSAGE);
                        populateTable();
                        reset();
                }
            }
            catch(Exception exc){
                exc.printStackTrace();
            }
        }
        
    }//GEN-LAST:event_jbtn_ExpelActionPerformed

    private void jtbl_DriversMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbl_DriversMouseClicked
        int row = jtbl_Drivers.getSelectedRow();
        if((evt.getButton() == MouseEvent.BUTTON1) && (evt.getClickCount() == 1)){
            String branch = jtbl_Drivers.getValueAt(row,0).toString();
            String agent = jtbl_Drivers.getValueAt(row,1).toString();
            String car = jtbl_Drivers.getValueAt(row,2).toString();
            String first = jtbl_Drivers.getValueAt(row,3).toString();
            String last = jtbl_Drivers.getValueAt(row,4).toString();
            String contact = jtbl_Drivers.getValueAt(row,5).toString();
            
            jComboBox_Branch.setSelectedItem(branch);
            jComboBox_Agent.setSelectedItem(agent);
            jComboBox_Car.setSelectedItem(car);
            jtxt_First.setText(first);
            jtxt_Last.setText(last);
            jtxt_Contact.setText(contact);
        }
        else if((evt.getButton() == MouseEvent.BUTTON1) && (evt.getClickCount() == 2)){
            reset();
        }
    }//GEN-LAST:event_jtbl_DriversMouseClicked

    private void jComboBox_BranchItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox_BranchItemStateChanged
        
        try{
            jComboBox_Agent.removeAllItems();
            String branch = jComboBox_Branch.getSelectedItem().toString();
            ArrayList<String> agents = agentDAO.getAgentsByBranch(branch);
            
            for(int i = 0;i<agents.size();i++){
                jComboBox_Agent.addItem(agents.get(i));
            }
        }
        catch(Exception exc){
            exc.printStackTrace();
        }
    }//GEN-LAST:event_jComboBox_BranchItemStateChanged

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        HomePageUI homeUI = new HomePageUI(accountID);
        setVisible(false);
        homeUI.setVisible(true);
    }//GEN-LAST:event_jLabel9MouseClicked

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        HomePageUI homeUI = new HomePageUI(accountID);
        homeUI.setVisible(true);
    }//GEN-LAST:event_formWindowClosed

    private void jtxt_SearchMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxt_SearchMouseEntered
        if(jtxt_Search.getText().contains("Search Driver...")){
            jtxt_Search.setText("");
        }
    }//GEN-LAST:event_jtxt_SearchMouseEntered

    private void jtxt_SearchMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxt_SearchMouseExited
        if(jtxt_Search.getText().isEmpty()){
            jtxt_Search.setText("Search Driver...");
        }
    }//GEN-LAST:event_jtxt_SearchMouseExited

    private void jtxt_SearchKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxt_SearchKeyTyped
        String search = jtxt_Search.getText().trim();
        try{
            if(search.isEmpty()){
                ArrayList<Driver> list = driverDAO.getAllDrivers();
                DriverTableModel model = new DriverTableModel(list);
                jtbl_Drivers.setModel(model);
            }
            else{
                ArrayList<Driver> list = driverDAO.searchDriver(search);
                DriverTableModel model = new DriverTableModel(list);
                jtbl_Drivers.setModel(model);
            }
        }
        catch(Exception exc){
            exc.printStackTrace();
        }
    }//GEN-LAST:event_jtxt_SearchKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DriverUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DriverUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DriverUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DriverUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DriverUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox_Agent;
    private javax.swing.JComboBox<String> jComboBox_Branch;
    private javax.swing.JComboBox<String> jComboBox_Car;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtn_Expel;
    private javax.swing.JButton jbtn_Register;
    private javax.swing.JButton jbtn_Update;
    private javax.swing.JTable jtbl_Drivers;
    private javax.swing.JTextField jtxt_Contact;
    private javax.swing.JTextField jtxt_First;
    private javax.swing.JTextField jtxt_Last;
    private javax.swing.JTextField jtxt_Search;
    // End of variables declaration//GEN-END:variables

    private void reset(){
        jComboBox_Branch.setSelectedIndex(0);
        jComboBox_Agent.setSelectedIndex(0);
        jComboBox_Car.setSelectedIndex(0);
        jtxt_First.setText("");
        jtxt_Last.setText("");
        jtxt_Contact.setText("");
    }
    
    private void populateGUI(){
        try{
            ArrayList<Branch> branches = branchDAO.getAllBranches();
            ArrayList<Car> cars = carDAO.getAllCars();
            
            for(int i = 0;i<branches.size();i++){
                jComboBox_Branch.addItem(branches.get(i).getBranchName());
            }
            
            for(int i = 0;i<cars.size();i++){
                jComboBox_Car.addItem(cars.get(i).getCarName());
            }
        }
        catch(Exception exc){
            exc.printStackTrace();
        }
    }
    
    private void populateTable(){
        try{
            ArrayList<Driver> list = driverDAO.getAllDrivers();
            DriverTableModel model = new DriverTableModel(list);
            jtbl_Drivers.setModel(model);
        }
        catch(Exception exc){
            exc.printStackTrace();
        }
    }
}
